library(forecast)
library(TSstudio)
library(tseries)
library(xts)
sales <- read.csv(file.choose())
sales <- as.numeric(unlist(sales))
View(sales)
str(sales)
head(sales)
sales <- ts(sales,start = c(1987,1),frequency = 12)
str(sales)
class(sales)
print(sales)
plot(sales)
ggseasonplot(sales)
ggsubseriesplot(sales)
gglagplot(sales)
plot(decompose(sales))
periodicity(sales)
Train <- window(sales, start=c(1987,1), end=c(1993,12), frequency=12) 
Test <- window(sales, start=c(1987,1), frequency=12) 
plot(Train)
plot(Test)
adf.test(sales)
adf.test(Train)
adf.test(diff(log(Train)))
plot(diff(log(Train)))
library(rlang)
library(tseries)
library(TSstudio)
ts_cor(Train)
ts_cor(diff(log(Train)))
library(Metrics)
sesmodel <- HoltWinters(Train, beta = FALSE, gamma = FALSE)
sesmodel
seshwforecast <- forecast(sesmodel, h = 12)
plot(sesmodel)
plot(seshwforecast) 
sesmodel1 <- ses(Train, h = 12)
plot(sesmodel)
kpss.test(sales)


